kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-docker
  template:
    metadata:
      labels:
        app: react-docker
    spec:
      containers:
      - name: react-docker
        image: registry.gitlab.com/galv-vmw-july-2022/capstone/petconnect-frontend
        ports:
        - containerPort: 80
