kind: Deployment
apiVersion: apps/v1
metadata:
  name: pet-connect-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-connect-frontend
  template:
    metadata:
      labels:
        app: pet-connect-frontend
    spec:
      containers:
      - name: pet-connect-frontend
        image: justinchen87/petconnect
        ports:
        - containerPort: 80
