apiVersion: v1
kind: Service
metadata:
  name: petConnect-load-balancer
  labels:
    app: pet-connect-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    # nodePort: 31000
  selector:
    app: pet-connect-frontend
